<?php

namespace InformeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SalidasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalidasRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array(), array('inicio' => 'ASC'));
    }

    public function findSalidas($informe_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT s FROM InformeBundle:Salidas s
                    JOIN s.informe f
                    WHERE f.id = :informe
                    AND s.tipo <> :tipo
                    ORDER BY s.inicio ASC"
            )
            ->setParameter('informe', $informe_id)
            ->setParameter('tipo', 'Visitante')
            ->getResult();
    }

    public function findByVisitantes($informe_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT s FROM InformeBundle:Salidas s
                    JOIN s.informe f
                    WHERE f.id = :informe
                    AND s.tipo = :tipo
                    ORDER BY s.inicio ASC"
            )
            ->setParameter('informe', $informe_id)
            ->setParameter('tipo', 'Visitante')
            ->getResult();
    }
}
