<?php

namespace InformeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SalidasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalidasRepository extends EntityRepository
{
}
